<div class="menu">
    <nav>
        <ul class="menuLateral">
            <li><a href="index.html"><strong>home</strong></a></li>
            <li><a href="sol.html"><strong>sol</strong></a></li>
            <li><a href="#"><strong>planetas</strong></a>
                <ul>
                    <li><a href="#">rochosos</a>
                        <ul>
                            <li><a href="mercurio.html">mercúrio</a></li>
                            <li><a href="venus.html">vênus</a></li>
                            <li><a href="terra.html">terra</a></li>
                            <li><a href="marte.html">marte</a></li>
                        </ul>
                    </li>
                    <li><a href="#">gasosos</a>
                        <ul>
                            <li><a href="jupiter.html">júpiter</a></li>
                            <li><a href="saturno.html">saturno</a></li>
                            <li><a href="urano.html">urano</a></li>
                            <li><a href="netuno.html">netuno</a></li>
                        </ul>
                    </li>
                    <li><a href="#">anões</a>
                        <ul>
                            <li><a href="plutao.html">plutão</a></li>
                            <li><a href="haumea.html">haumea</a></li>
                            <li><a href="makemake.html">makemake</a></li>
                            <li><a href="eris.html">éris</a></li>
                            <li><a href="ceres.html">ceres</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Outros</a>
                        <ul>
                            <li><a href="cinturaokuiper.html">Cinturão de Kuiper</a></li>
                            <li><a href="discodisperso.html">Disco Disperso</a></li>
                            <li><a href="nuvemoort.html">Nuvem de Oort</a></li>
                            <li><a href="cometas.html">cometas</a></li>
                        </ul>
                </ul>

            </li>
            </li>
            <li><a href="audiovideo.html"><strong>audio e video</strong></a></li>
            <li><a href="contato.html"><strong>contato</strong></a></li>
        </ul>
    </nav>
</div>